
make_data = function(n, nsets, seeds){
  
  t = seq(0,1, 0.01)
  
  X.pca2synth = function(nsamples){
    
    nPC1 = runif(nsamples, min = dgobj$Xscorepar[1,1], max = dgobj$Xscorepar[2,1])
    nPC2 = runif(nsamples, min = dgobj$Xscorepar[1,2], max = dgobj$Xscorepar[2,2])
    nPC3 = runif(nsamples, min = dgobj$Xscorepar[1,3], max = dgobj$Xscorepar[2,3])
    nPC4 = runif(nsamples, min = dgobj$Xscorepar[1,4], max = dgobj$Xscorepar[2,4])
    nPC5 = runif(nsamples, min = dgobj$Xscorepar[1,5], max = dgobj$Xscorepar[2,5])
    nPC6 = runif(nsamples, min = dgobj$Xscorepar[1,6], max = dgobj$Xscorepar[2,6])
    new_scores = cbind(nPC1, nPC2, nPC3, nPC4, nPC5, nPC6)
    
    new_mat = c()
    
    for (i in 1:nsamples) {
      
      mean = eval.fd(t, dgobj$Xmu)
      
      pc1 = eval.fd(t, dgobj$Xharm[1])*new_scores[i,1]
      pc2 = eval.fd(t, dgobj$Xharm[2])*new_scores[i,2]
      pc3 = eval.fd(t, dgobj$Xharm[3])*new_scores[i,3]
      pc4 = eval.fd(t, dgobj$Xharm[4])*new_scores[i,4]
      pc5 = eval.fd(t, dgobj$Xharm[5])*new_scores[i,5]
      pc6 = eval.fd(t, dgobj$Xharm[6])*new_scores[i,6]
      obs = mean+pc1+pc2+pc3+pc4+pc5+pc6
      
      new_mat = cbind(new_mat, obs)
      
    }
    
    
    
    return(smooth.basis(argvals = t, y = new_mat, fdParobj = create.bspline.basis(c(0,1), 50, 4))$fd)
    
  }
  
  
  E.pca2synth = function(nsamples){
    
    nPC1 = rnorm(nsamples, 0, sd = dgobj$Escorepar[1])
    nPC2 = rnorm(nsamples, 0, sd = dgobj$Escorepar[2])
    nPC3 = rnorm(nsamples, 0, sd = dgobj$Escorepar[3])
    nPC4 = rnorm(nsamples, 0, sd = dgobj$Escorepar[4])
    nPC5 = rnorm(nsamples, 0, sd = dgobj$Escorepar[5])
    nPC6 = rnorm(nsamples, 0, sd = dgobj$Escorepar[6])
    nPC7 = rnorm(nsamples, 0, sd = dgobj$Escorepar[7])
    nPC8 = rnorm(nsamples, 0, sd = dgobj$Escorepar[8])
    
    new_scores = cbind(nPC1, nPC2, nPC3, nPC4, nPC5, nPC6, nPC7, nPC8)
    
    new_mat = c()
    
    for (i in 1:nsamples) {
      
      mean = eval.fd(t, dgobj$Emu)
      
      pc1 = eval.fd(t, dgobj$Eharm[1])*new_scores[i,1]
      pc2 = eval.fd(t, dgobj$Eharm[2])*new_scores[i,2]
      pc3 = eval.fd(t, dgobj$Eharm[3])*new_scores[i,3]
      pc4 = eval.fd(t, dgobj$Eharm[4])*new_scores[i,4]
      pc5 = eval.fd(t, dgobj$Eharm[5])*new_scores[i,5]
      pc6 = eval.fd(t, dgobj$Eharm[6])*new_scores[i,6]
      pc7 = eval.fd(t, dgobj$Eharm[7])*new_scores[i,7]
      pc8 = eval.fd(t, dgobj$Eharm[8])*new_scores[i,8]
  
      obs = mean+pc1+pc2+pc3+pc4+pc5+pc6+pc7+pc8
      
      new_mat = cbind(new_mat, obs)
      
    }
    
    
    
    return(fd(new_mat, create.bspline.basis(c(0,1), 101, 4)))
    
  }
  
  sim.set.list = vector('list', nsets)
  
  for(i in 1:nsets) {
    
    set.seed(seeds[i])
    
    print(paste("Simulating set ", i, " of ", nsets))
    
    x.fd = X.pca2synth(nsamples = n)
    
    xfdlist = list(x.fd)
    
    y.fd.mod = predict.FEM.HFLM(model = dgobj$Model, xfdlist = xfdlist, nfine = 201)
    
    y.fd = y.fd.mod$yhat.fd
    
    
    # simulate errors
    
    error.fd = E.pca2synth(nsamples = n)
    
    
    y.e.fd = y.fd+error.fd
    
    d.list = list("seed" = seeds[i], "nfine" = 201, "x.fd" = x.fd, "y.fd" = y.fd, "error.fd" = error.fd, "yplusE" = y.e.fd)
    
    sim.set.list[[i]] <- d.list
    
  }
  
  
  
  details = "Generative Model: OLS FEM HFLM with order = 1, m = 6 (nbasis = 21) and lambda = 0, fit to 372 time normalised 
sagital knee and ankle curves represented on a 101 bspline basis registered to toe off with ankle prediciting knee.

New X Data: data generated from functional principal components of the original ankle curves. 
Original data was decomposed into 6 fPCs explaining 95% of the variance. New coefficient samples were then drawn 
from a uniform distribution spanning the range of the respective original fPC scores. 100 sets of 500 curves were 
generated and fit with a b-spline basis (nbasis = 50) to reduce computational overhead moving forward.

New Y Data: simulated X data was then fed into the estimated model with integration happening across 101 points in 
the s direction. Y data was fit with the same b-spline basis as the X data. 

Error: the error term was generated by applying the same process as the X data to the residuals from the original fit 
except drawing from a normal distribution with mean and sd equal to the mean and sd of the respective fPCA scores of the errror"
  
  Simulated.Data = list("Details" = details, "Model" = list("alpha" = dgobj$Model$intercept.fd, "beta" = dgobj$Model$beta.est.list[[1]]), 
                        "Data" = sim.set.list)
  
  
  
  return(Simulated.Data)
  
}